version: "3.8"
services:
  nginx:
    build: ./nginx
    image: nginx-punbb
    volumes:
      - ../src:/var/www/html/extensions/subforums
    ports:
      - "80:80"
    links:
      - php

  php:
    build: ./php
    image: php-punbb
    volumes:
      - ../src:/var/www/html/extensions/subforums
    links:
      - db

  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - ./store/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: punbb
      MYSQL_USER: punbb
      MYSQL_PASSWORD: secret
    user: "1000:50"
